apiVersion: apps/v1
kind: Deployment
metadata:
  name: servidor-go-deployment
spec:
  replicas: 2  # Será ajustado dinamicamente pelos testes (2, 4, 6, 8, 10)
  selector:
    matchLabels:
      app: servidor-go
  template:
    metadata:
      labels:
        app: servidor-go
    spec:
      containers:
        - name: servidor-go
          image: bia18/projetok-servidor-go:latest
          imagePullPolicy: Always  # Sempre baixar a versão mais recente do Docker Hub
          ports:
            - containerPort: 8000
          command: ["./servidor"]
          args: ["--porta", "8000"]
          resources:
            requests:
              memory: "768Mi"   # Aumentado: mais buffer para cache
              cpu: "1500m"      # 1.5 CPU cores por pod
            limits:
              memory: "1.5Gi"   # Aumentado para melhor throughput
              cpu: "3000m"      # 3 CPU cores por pod 
