# Dockerfile para Servidor Python
FROM python:3.11-alpine

WORKDIR /app

# Copiar código fonte do servidor Python
COPY ["src/servidor (local)/servidor.py", "."]

# Expor porta
EXPOSE 8000

# Comando padrão
CMD ["python", "servidor.py", "--porta", "8000"]
