kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: projetok
nodes:
- role: control-plane
  extraPortMappings:
  # NodePort para servidor Go (30001)
  - containerPort: 30001
    hostPort: 30001
    protocol: TCP
  # NodePort para servidor Python (30002)
  - containerPort: 30002
    hostPort: 30002
    protocol: TCP
  # Porta adicional para futuros testes
  - containerPort: 30003
    hostPort: 30003
    protocol: TCP
